# Generated by Django 3.1.1 on 2021-01-10 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_products_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
    ]
