# Generated by Django 3.1.1 on 2021-01-14 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='individual_picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='team/'),
            preserve_default=False,
        ),
    ]
