# Generated by Django 3.1.1 on 2021-01-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_team_individual_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='description',
            new_name='introduction',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='details',
            new_name='paragraph_1',
        ),
        migrations.AddField(
            model_name='products',
            name='paragraph_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
